# 🚀 TopCV Crawler: Thu thập việc làm IT lịch sử từ Wayback Machine Sitemaps (2022 - 2026)

Notebook phục vụ thu thập dữ liệu việc làm ngành Công nghệ Thông tin & Dữ liệu cho đồ án **JobLens Vietnam**:
- **Cơ chế thu thập tối ưu (curl_cffi requests.Session):**
  - **Vượt rào cản Cloudflare:** Sử dụng `curl_cffi` giả lập chuẩn xác TLS fingerprint của Chrome 120, loại bỏ hoàn toàn lỗi chặn 403.
  - **Crawl tuần tự:** dùng một session curl_cffi, gửi từng request và nghỉ 2.5–5 giây giữa các URL.
  - **Không quét mù (Zero Guessing):** Tải lại chính xác các bản lưu trữ `sitemap.xml` của TopCV trên Internet Archive (`web.archive.org`) qua từng năm (2022, 2023, 2025, 2026) và Live Sitemaps.
  - **100% việc làm IT có thật:** Lọc từ khóa IT ngay trên file sitemap XML, mỗi request gửi đi đều nhắm thẳng vào bài đăng IT chuẩn xác.
  - **Đã gom sẵn 7.074 URLs:** Toàn bộ liên kết việc làm IT đã được lọc và lưu sẵn tại `data/raw/topcv_it_job_urls.csv`.

In [4]:
import sys
from pathlib import Path
import pandas as pd

# Thêm thư mục gốc vào PYTHONPATH
root_dir = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))

from src.crawler.topcv_crawler import TopCVCrawler

# Khởi tạo crawler sử dụng curl_cffi requests.Session (Chrome 120 TLS fingerprint)
crawler = TopCVCrawler()
print("TopCVCrawler (curl_cffi) đã sẵn sàng!")

TopCVCrawler (curl_cffi) đã sẵn sàng!

## 1. Test nhanh: Tải 1 file Sitemap từ Wayback Machine (Năm 2022)
Tải thử bản lưu trữ `jobs_0.xml` ngày 04/07/2022 từ Internet Archive để kiểm chứng tốc độ trích xuất:

In [2]:
# Tải thử 1 file sitemap đầu tiên của năm 2022 từ Wayback Machine
it_urls_2022, url_date_map = crawler.get_it_urls_from_wayback_snapshot(
    sub_ts="20220704052951",
    sitemap_count=1
)

print(f"-> Thu thập thành công {len(it_urls_2022)} link việc làm IT từ sitemap năm 2022!")
print("Ví dụ 3 link đầu tiên:")
for u in it_urls_2022[:3]:
    print(" -", u, "| Ngày đăng (lastmod):", url_date_map.get(u))

Wayback (2022):   0%|          | 0/1 [00:02<?, ?it/s]

KeyboardInterrupt:

---
## 2. BƯỚC 1: GOM DANH SÁCH URL TỪ TẤT CẢ SITEMAPS (Wayback + Live)
Tải tất cả các file sub-sitemaps (2022 - 2026), lọc slug theo `TECH_JOB_KEYWORDS`, khử trùng lặp và lưu ra file `data/raw/topcv_it_job_urls.csv`.
> 💡 *Hiện tại repo đã gom sẵn đầy đủ **7.074 URLs IT** tại `data/raw/topcv_it_job_urls.csv`. Bạn có thể bỏ qua bước này nếu không cần quét lại từ đầu.*

In [4]:
# BƯỚC 1: Gom và lưu danh sách link IT (chỉ chạy nếu muốn quét lại từ đầu)
# df_urls = crawler.collect_urls_from_sitemaps(
#     save_path=str(root_dir / "data" / "raw" / "topcv_it_job_urls.csv")
# )

# Đọc danh sách URL đã có sẵn để kiểm tra
url_list_path = root_dir / "data" / "raw" / "topcv_it_job_urls.csv"
df_urls = pd.read_csv(url_list_path)
print(f"Tổng số URL IT có sẵn: {len(df_urls):,}")
df_urls.head()

======================================================================
🔍 BẮT ĐẦU BƯỚC 1: GOM DANH SÁCH LINK VIỆC LÀM IT TỪ TẤT CẢ SITEMAPS
======================================================================

📂 Đang quét sitemap: WAYBACK SNAPSHOT T07/2022...

Wayback (2022): 100%|██████████| 16/16 [04:48<00:00, 18.05s/it]

-> Thu được 1,130 link IT từ Wayback Snapshot T07/2022.
-> Thêm mới 1,130 URL độc bản (Tổng hiện có: 1,130)

📂 Đang quét sitemap: WAYBACK SNAPSHOT T12/2022...

Wayback (2022): 100%|██████████| 16/16 [05:08<00:00, 19.29s/it]

-> Thu được 741 link IT từ Wayback Snapshot T12/2022.
-> Thêm mới 741 URL độc bản (Tổng hiện có: 1,871)

📂 Đang quét sitemap: WAYBACK SNAPSHOT T03/2023...

Wayback (2023): 100%|██████████| 19/19 [06:20<00:00, 20.05s/it]

-> Thu được 280 link IT từ Wayback Snapshot T03/2023.
-> Thêm mới 273 URL độc bản (Tổng hiện có: 2,144)

📂 Đang quét sitemap: WAYBACK SNAPSHOT T06/2023...

Wayback (2023): 100%|██████████| 19/19 [05:48<00:00, 18.34s/it]

-> Thu được 772 link IT từ Wayback Snapshot T06/2023.
-> Thêm mới 753 URL độc bản (Tổng hiện có: 2,897)

📂 Đang quét sitemap: WAYBACK SNAPSHOT T09/2025...

Wayback (2025): 100%|██████████| 100/100 [33:48<00:00, 20.29s/it]

-> Thu được 145 link IT từ Wayback Snapshot T09/2025.
-> Thêm mới 145 URL độc bản (Tổng hiện có: 3,042)

📂 Đang quét sitemap: LIVE TOPCV SITEMAPS (TOÀN BỘ ~223 SITEMAPS)...

Live TopCV (2026): 100%|██████████| 223/223 [01:45<00:00,  2.12it/s]

-> Thu được 4,036 link IT từ Live TopCV Sitemaps (Toàn bộ ~223 sitemaps).
-> Thêm mới 4,032 URL độc bản (Tổng hiện có: 7,074)

======================================================================
✅ HOÀN TẤT GOM URL! Tổng cộng: 7,074 link việc làm IT độc bản.

📊 Phân bố link việc làm IT theo mốc:
year
2022    1871
2023    1026
2025     145
2026    4032
📁 Tệp danh sách URL đã lưu tại: g:\hoc_tap\IntroDS\project_intro_ds\data\raw\topcv_it_job_urls.csv
======================================================================

,url,posted_date_fallback,snapshot_period,year,snapshot_label
0,https://www.topcv.vn/viec-lam/embedded-softwar...,2022-05-11,07/2022,2022,Wayback Snapshot T07/2022
1,https://www.topcv.vn/viec-lam/lap-trinh-php/20...,2022-05-11,07/2022,2022,Wayback Snapshot T07/2022
2,https://www.topcv.vn/viec-lam/senior-magento-d...,2022-05-10,07/2022,2022,Wayback Snapshot T07/2022
3,https://www.topcv.vn/viec-lam/ruby-on-rails/24...,2022-05-10,07/2022,2022,Wayback Snapshot T07/2022
4,https://www.topcv.vn/viec-lam/nodejs-developer...,2022-05-11,07/2022,2022,Wayback Snapshot T07/2022

---
## 3. BƯỚC 2: CÀO CHI TIẾT JD TUẦN TỰ BẰNG CURL_CFFI

Đọc danh sách URL ở Bước 1 và crawl tuần tự bằng `curl_cffi.requests.Session`, mỗi lần một URL.
- Nghỉ 2.5–5 giây giữa các request.
- Lưu checkpoint CSV và state sau mỗi 50 jobs; lỗi 403/429 không bị đánh dấu nhầm là đã xử lý.
- Chạy lại với `resume=True` để tiếp tục từ các URL còn lại.

> Có thể chạy qua Terminal để quá trình ổn định hơn:
> ```bash
> python src/crawler/run_crawl.py --step crawl
> ```

In [5]:
# BƯỚC 2: Crawl chi tiết từ danh sách URL
# Để test nhanh, giữ limit=20; dùng limit=None để crawl toàn bộ danh sách.
df_jobs = crawler.crawl_jobs_from_url_file(
    url_file_path=str(root_dir / "data" / "raw" / "topcv_it_job_urls.csv"),
    save_path=str(root_dir / "data" / "raw" / "topcv_it_jobs_wayback.csv"),
    limit=None,
    save_every=20,
    resume=True,
)

print(f"\n✅ Hoàn tất! Tổng số jobs IT thu thập được: {len(df_jobs):,}")
df_jobs.head()

-> Đã có 5,326 jobs IT được lưu sẵn trong file checkpoint.
======================================================================
BẮT ĐẦU CÀO CHI TIẾT JD: CURL_CFFI, TUẦN TỰ MỘT LUỒNG
-> Tổng link trong file   : 7,074
-> Đã xử lý trước đó      : 7,646 (Jobs IT đã lưu: 5,326)
-> Cần cào đợt này        : 0
-> Mỗi lần chỉ gửi một request; nghỉ 2.5–5 giây giữa các URL
======================================================================
🎉 Toàn bộ danh sách link đã được xử lý.

✅ Hoàn tất! Tổng số jobs IT thu thập được: 5,326

,job_title,company_name,salary_raw,experience_raw,location_raw,posted_date,deadline_date,job_description_raw,job_requirements_raw,url
0,Backend Developer(Golang- Upto 40 Triệu/Tháng),Công Ty Cổ Phần Lozi Việt Nam (Loship),Thoả thuận,1 năm,Hồ Chí Minh,2022-07-22,2022-08-30,Mô tả công việc\nResponsibilities\nAt Lozi we ...,Yêu cầu ứng viên\nRequirements\nAt least 6 mon...,https://www.topcv.vn/viec-lam/backend-develope...
1,IOS Developer,Công Ty Cổ Phần Lozi Việt Nam (Loship),Thoả thuận,1 năm,Hồ Chí Minh,2022-06-01,2022-07-21,Mô tả công việc\nResponsibilities\nWork closel...,Yêu cầu ứng viên\nRequirements\nMore than 6 mo...,https://www.topcv.vn/viec-lam/ios-developer/69...
2,Senior SoftwareProject Manager,Công ty Cổ phần TOPCV Việt Nam,Thoả thuận,3 năm,Hà Nội,2022-08-31,2022-09-30,Mô tả công việc\n• Ensure that project teams a...,Yêu cầu ứng viên\n• A degree in IT / Computer ...,https://www.topcv.vn/brand/topcv/tuyen-dung/se...
3,Chuyên Viên Kiểm Thử Phần Mềm-Tester,Công ty Cổ phần TOPCV Việt Nam,Thoả thuận,1 năm,Hà Nội,2022-06-14,2022-07-11,"Mô tả công việc\nTìm hiểu, nghiên cứu, phân tí...",Yêu cầu ứng viên\nTốt nghiệp CĐ/ĐH\nCó ít nhất...,https://www.topcv.vn/brand/topcv/tuyen-dung/ch...
4,Frontend Developer(Reactjs),Công ty Cổ phần TOPCV Việt Nam,Tới 18 triệu,1 năm,Hà Nội,2022-06-23,2022-07-03,Mô tả công việc\nPhát triển dự án và các sản p...,"Yêu cầu ứng viên\nTốt nghiệp ĐH, ưu tiên các c...",https://www.topcv.vn/brand/topcv/tuyen-dung/fr...